In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

In [2]:
df=pd.read_csv("C:\\Users\\Hp\\Downloads\\kidney_disease.csv")
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [3]:
df["classification"].unique()

array(['ckd', 'ckd\t', 'notckd'], dtype=object)

In [4]:
df['classification'] =df['classification'].replace(to_replace = 'ckd\t', value = 'ckd')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [6]:
pd.set_option('display.max_columns', None)
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [7]:
df.drop_duplicates()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [8]:
df.drop(["id"],axis=1,inplace=True)

In [9]:
df['rc']=pd.to_numeric(df['rc'],errors='coerce')

In [10]:
df['pcv']=pd.to_numeric(df['pcv'],errors='coerce')

In [11]:
df['wc']=pd.to_numeric(df['wc'],errors='coerce')

In [12]:
categorical_features = df.select_dtypes(include = ["object","bool"]).columns
numerical_features = df.select_dtypes(include = ["int64","float64"]).columns

In [13]:
df[categorical_features]=df[categorical_features].astype("str")

In [14]:
df[numerical_features]=df[numerical_features].replace(np.nan,0)

In [15]:
df[numerical_features] = df[numerical_features].fillna(df[numerical_features].median())

In [16]:
df[categorical_features]=df[categorical_features].replace(np.nan,0)

In [17]:
df[categorical_features] = df[categorical_features].fillna(df[categorical_features].mode())

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             400 non-null    float64
 1   bp              400 non-null    float64
 2   sg              400 non-null    float64
 3   al              400 non-null    float64
 4   su              400 non-null    float64
 5   rbc             400 non-null    object
 6   pc              400 non-null    object
 7   pcc             400 non-null    object
 8   ba              400 non-null    object
 9   bgr             400 non-null    float64
 10  bu              400 non-null    float64
 11  sc              400 non-null    float64
 12  sod             400 non-null    float64
 13  pot             400 non-null    float64
 14  hemo            400 non-null    float64
 15  pcv             400 non-null    float64
 16  wc              400 non-null    float64
 17  rc              400 non-null    float64
 18  htn             400 non-null    object
 19  dm              400 non-null    object
 20  cad             400 non-null    object
 21  appet           400 non-null    object
 22  pe              400 non-null    object
 23  ane             400 non-null    object
 24  classification  400 non-null    object
dtypes: float64(14), object(11)
memory usage: 78.2+ KB

In [19]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
df[categorical_features] = encoder.fit_transform(df[categorical_features])

In [20]:
df

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,1.0,2.0,1.0,1.0,121.0,36.0,1.2,0.0,0.0,15.4,44.0,7800.0,5.2,2.0,5.0,2.0,0.0,1.0,1.0,0.0
1,7.0,50.0,1.020,4.0,0.0,1.0,2.0,1.0,1.0,0.0,18.0,0.8,0.0,0.0,11.3,38.0,6000.0,0.0,1.0,4.0,2.0,0.0,1.0,1.0,0.0
2,62.0,80.0,1.010,2.0,3.0,2.0,2.0,1.0,1.0,423.0,53.0,1.8,0.0,0.0,9.6,31.0,7500.0,0.0,1.0,5.0,2.0,2.0,1.0,2.0,0.0
3,48.0,70.0,1.005,4.0,0.0,2.0,0.0,2.0,1.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,2.0,4.0,2.0,2.0,2.0,2.0,0.0
4,51.0,80.0,1.010,2.0,0.0,2.0,2.0,1.0,1.0,106.0,26.0,1.4,0.0,0.0,11.6,35.0,7300.0,4.6,1.0,4.0,2.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,2.0,2.0,1.0,1.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9,1.0,4.0,2.0,0.0,1.0,1.0,1.0
396,42.0,70.0,1.025,0.0,0.0,2.0,2.0,1.0,1.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,7800.0,6.2,1.0,4.0,2.0,0.0,1.0,1.0,1.0
397,12.0,80.0,1.020,0.0,0.0,2.0,2.0,1.0,1.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4,1.0,4.0,2.0,0.0,1.0,1.0,1.0
398,17.0,60.0,1.025,0.0,0.0,2.0,2.0,1.0,1.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9,1.0,4.0,2.0,0.0,1.0,1.0,1.0
399,58.0,80.0,1.025,0.0,0.0,2.0,2.0,1.0,1.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1,1.0,4.0,2.0,0.0,1.0,1.0,1.0

In [21]:
x=df.drop("classification",axis=1)
y=df["classification"]

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [23]:
from sklearn.ensemble import GradientBoostingClassifier
gb_model= GradientBoostingClassifier()
gb_model.fit(x_train,y_train)

y_pred_train=gb_model.predict(x_train)
y_pred_test=gb_model.predict(x_test)

from sklearn.metrics import accuracy_score
print("train_accuracy:",accuracy_score(y_train,y_pred_train))
print("test_accuracy:",accuracy_score(y_test,y_pred_test))


from sklearn.model_selection import cross_val_score
scores=cross_val_score(gb_model,x,y,cv=5)
print("cross validation score:",scores.mean())

train_accuracy: 1.0
test_accuracy: 1.0
cross validation score: 0.9824999999999999

In [24]:
from sklearn.model_selection import GridSearchCV
estimator=GradientBoostingClassifier()
param_grid={"n_estimators":[5,10,15,20],"learning_rate":[0.1,0.2,0.3,0.5,0.8,1]}
grid=GridSearchCV(estimator,param_grid,cv=5,scoring="accuracy")
grid.fit(x_train,y_train)
print(grid.best_params_)
grid.best_estimator_

{'learning_rate': 0.8, 'n_estimators': 15}

GradientBoostingClassifier(learning_rate=0.8, n_estimators=15)

In [25]:
grid.best_estimator_.feature_importances_

array([4.03188752e-04, 2.66854115e-04, 2.01018597e-01, 2.55105801e-02,
       1.63869784e-03, 2.75736042e-03, 1.14182466e-03, 0.00000000e+00,
       0.00000000e+00, 3.74839230e-03, 2.72506195e-05, 4.36278004e-03,
       1.11901003e-04, 0.00000000e+00, 6.58800566e-01, 4.91725459e-03,
       1.66155119e-03, 6.98393401e-02, 2.36062833e-02, 1.87243122e-04,
       0.00000000e+00, 0.00000000e+00, 3.35338006e-07, 0.00000000e+00])

In [26]:
feats=pd.DataFrame(data=grid.best_estimator_.feature_importances_,index=x.columns,columns=["importance"])
important_features=feats[feats["importance"]>0.01]
important_features

      importance
sg      0.201019
al      0.025511
hemo    0.658801
rc      0.069839
htn     0.023606

In [27]:
important_features_list=feats[feats["importance"]>0.01].index.to_list()
important_features_list

['sg', 'al', 'hemo', 'rc', 'htn']

In [30]:
x=x[important_features_list]
y=df["classification"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

gb_bhp=GradientBoostingClassifier(n_estimators=15,learning_rate=0.8)
gb_bhp.fit(x_train,y_train)

ypred_train=gb_bhp.predict(x_train)
predictions=gb_bhp.predict(x_test)

from sklearn.metrics import accuracy_score
print("train accuracy:",accuracy_score(y_train,ypred_train))
print("test accuracy:",accuracy_score(y_test,predictions))
scores=cross_val_score(gb_bhp,x,y,cv=5,)
print("cross validation score:",scores.mean())

train accuracy: 0.996875
test accuracy: 0.975
cross validation score: 0.9724999999999999